services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB:       linkhub
      POSTGRES_USER:     linkhub
      POSTGRES_PASSWORD: linkhub
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U linkhub"]
      interval: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: ["pnpm","dev","-p","3000"]
    environment:
      DATABASE_URL:       postgres://linkhub:linkhub@db:5432/linkhub?schema=public
      NEXTAUTH_SECRET:    ${NEXTAUTH_SECRET}
      GOOGLE_CLIENT_ID:   ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
