services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB:       linkhub
      POSTGRES_USER:     linkhub
      POSTGRES_PASSWORD: linkhub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U linkhub"]
      interval: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://linkhub:linkhub@db:5432/linkhub?schema=public
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "
        pnpm prisma migrate deploy &&
        pnpm prisma generate &&
        pnpm dev -p 3000
      "
    ports:
      - "3000:3000"

volumes:
  pgdata:
